repository:
  private: true
  has_issues: true
  has_projects: false
  has_wiki: false
  has_downloads: false
  default_branch: main
  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: true
  delete_branch_on_merge: true
  enable_automated_security_fixes: true
  enable_vulnerability_alerts: true
  allow_forking: true
  web_commit_signoff_required: true

labels:
  - name: bug
    color: '#d73a4a'
    description: Something isn't working
  - name: feature
    color: '#93E04B'
    description: New functionality
  - name: chore
    color: '#47C1D0'
    description: Some annoying work...
  - name: dependency
    color: '#fbca04'
    description: Dependabot doing its job

branches:
  - name: main
    protection:
      required_pull_request_reviews:
        required_approving_review_count: null
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
        require_last_push_approval: true
      required_status_checks:
        strict: true
      required_conversation_resolution: true
      lock_branch: true
      enforce_admins: true
      allow_deletions: false
      allow_force_pushes: false
