---
:position: after
:position_in_additional_file_patterns: after
:position_in_class: after
:position_in_factory: after
:position_in_fixture: after
:position_in_routes: after
:position_in_serializer: after
:position_in_test: after
:classified_sort: true
:exclude_controllers: true
:exclude_factories: false
:exclude_fixtures: true
:exclude_helpers: true
:exclude_scaffolds: true
:exclude_serializers: true
:exclude_sti_subclasses: false
:exclude_tests: true
:force: false
:format_markdown: true
:format_rdoc: false
:format_yard: false
:frozen: false
:ignore_model_sub_dir: false
:ignore_unknown_models: false
:include_version: false
:show_check_constraints: false
:show_complete_foreign_keys: false
:show_foreign_keys: true
:show_indexes: true
:simple_indexes: true
:sort: false
:timestamp: false
:trace: false
:with_comment: true
:with_column_comments: true
:with_table_comments: false
:active_admin: false
:command:
:debug: false
:hide_default_column_types: "json,jsonb,hstore"
:hide_limit_column_types: "integer,bigint,boolean"
:ignore_columns:
:ignore_routes:
:models: true
:routes: false
:skip_on_db_migrate: false
:target_action: :do_annotations
:wrapper: true
:wrapper_close: "rubocop:enable Lint/RedundantCopDisableDirective, Layout/LineLength, Style/AsciiComments"
:wrapper_open: "rubocop:disable Lint/RedundantCopDisableDirective, Layout/LineLength, Style/AsciiComments"
:classes_default_to_s: []
:additional_file_patterns: []
:model_dir:
  - app/models
:require: []
:root_dir:
  - ""
