require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - rubocop-capybara
  - rubocop-factory_bot

inherit_gem:
  pundit: config/rubocop-rspec.yml

AllCops:
  NewCops: enable
  Exclude:
    - bin/**/*
    - vendor/bundle/**/*
Layout/BeginEndAlignment:
  EnforcedStyleAlignWith: begin
Layout/BlockAlignment:
  EnforcedStyleAlignWith: start_of_block
Rails/ActionOrder:
  ExpectedOrder:
    - index
    - show
    - new
    - create
    - edit
    - update
    - destroy
Rails/LexicallyScopedActionFilter:
  Exclude:
    - app/controllers/application_controller.rb
RSpec/MessageSpies:
  EnforcedStyle: receive
Style/ClassAndModuleChildren:
  EnforcedStyle: compact
Style/Documentation:
  Enabled: false
# class module
