require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - rubocop-capybara
  - rubocop-factory_bot

inherit_gem:
  pundit: config/rubocop-rspec.yml

AllCops:
  NewCops: enable
  Exclude:
    - db/schema.rb
    - node_modules/**/*
    - bin/**/*
    - vendor/**/*

Layout/BeginEndAlignment:
  EnforcedStyleAlignWith: begin
Layout/BlockAlignment:
  EnforcedStyleAlignWith: start_of_block
Metrics/AbcSize:
  Exclude:
    - db/migrate/*.rb
Metrics/MethodLength:
  Exclude:
    - db/migrate/*.rb
Style/ClassAndModuleChildren:
  EnforcedStyle: compact
Style/Documentation:
  Enabled: false

Rails/ActionOrder:
  ExpectedOrder:
    - index
    - show
    - new
    - create
    - edit
    - update
    - destroy
Rails/LexicallyScopedActionFilter:
  Exclude:
    - app/controllers/application_controller.rb

RSpec/MessageSpies:
  EnforcedStyle: receive
