default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= Settings.database.primary.host %>
  port: <%= Settings.database.primary.port %>
  username: <%= Settings.database.primary.username %>
  password: <%= Settings.database.primary.password %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

cache: &cache
  <<: *default
  host: <%= Settings.database.cache.host %>
  port: <%= Settings.database.cache.port %>
  username: <%= Settings.database.cache.username %>
  password: <%= Settings.database.cache.password %>

cable: &cable
  <<: *default
  host: <%= Settings.database.cable.host %>
  port: <%= Settings.database.cable.port %>
  username: <%= Settings.database.cable.username %>
  password: <%= Settings.database.cable.password %>

development:
  primary:
    <<: *default
    database: <%= "#{Settings.app.name}_development" %>
  cache:
    <<: *cache
    database: cache_development
  cable:
    <<: *cable
    database: cable_development

test:
  primary:
    <<: *default
    database: <%= "#{Settings.app.name}_test" %>

production:
  primary:
    <<: *default
    database: <%= "#{Settings.app.name}_production" %>
  cache:
    <<: *cache
    database: cache_production
  cable:
    <<: *cable
    database: cable_production
