app:
  name: rails_boilerplate
  host: "https://rails-boilerplate.io"
mail:
  sender: noreply@rails-boilerplate.io
  support: support@rails-boilerplate.io
s3:
  endpoint:
  region:
  bucket:
  access_key_id:
  secret_access_key:
