app:
  name: rails_boilerplate
  host: "https://rails-boilerplate.io"
mail:
  sender: noreply@rails-boilerplate.io
  support: support@rails-boilerplate.io
pay:
  business:
    name: "Rails Boilerplate"
    address: "123 Main St"
