---
blacklisted_domains:
  - xxyxi.com
  - musiccode.me
  - sharklasers.com
  - guerrillamail.info
  - grr.la
  - guerrillamail.biz
  - guerrillamail.com
  - guerrillamail.de
  - guerrillamail.net
  - guerrillamail.org
  - guerrillamailblock.com
  - pokemail.net
  - spam4.me
  - 0hio0ak.com
  - 10mail.org
  - 10mail.tk
  - 127.life
  - 1mail.x24hr.com
  - 23.8.dnsabr.com
  - 32core.live
  - 34nm.com
  - 4dentalsolutions.com
  - 816qs.com
  - 888.dns-cloud.net
  - 8.dnsabr.com
  - 99email.xyz
  - actitz.site
  - adaov.com
  - adult-work.info
  - aenikaufa.com
  - ahem.email
  - ahem-email.com
  - aintcheap.com
  - altmails.com
  - amail4.me
  - amail.club
  - anomail.club
  - anonymized.org
  - anywhere.pw
  - appzily.com
  - asia.dnsabr.com
  - badlion.co.uk
  - bambase.com
  - bambotv.com
  - bareed.ws
  - barretodrums.com
  - b.cr.cloudns.asia
  - bd.dns-cloud.net
  - bestofdedicated.com
  - besttempmail.com
  - billseo.com
  - biyac.com
  - blackturtle.xyz
  - budaya-tionghoa.com
  - budayationghoa.com
  - burgas.vip
  - buybacklink.biz
  - buy-blog.com
  - bylup.com
  - cars2.club
  - chapedia.net
  - chapedia.org
  - chasefreedomactivate.com
  - chiet.ru
  - cloud-mail.top
  - cmail.club
  - contactwithme.com
  - coolmailcool.com
  - corona.is.bullsht.dedyn.io
  - cpmail.life
  - cr.cloudns.asia
  - crepeau12.com
  - cudimex.com
  - cuoly.com
  - cxmyal.com
  - datenschutz.ru
  - dsgvo.ru
  - dencxvo.com
  - deps.cf
  - desoz.com
  - dhivehinews.site
  - diptoes.com
  - disbox.net
  - disbox.org
  - discard.email
  - discardmail.com
  - discardmail.computer
  - discardmail.de
  - discardmail.live
  - discardmail.ninja
  - disdraplo.com
  - dispomail.xyz
  - disposable-email.ml
  - disposable.ml
  - doc-mail.net
  - dristypat.com
  - dropmail.me
  - duck2.club
  - dvd.dnsabr.com
  - dvd.dns-cloud.net
  - dznf.net
  - easy-trash-mail.com
  - emailisvalid.com
  - email-jetable.biz.st
  - email-jetable.co.tv
  - email-jetable.cz.cc
  - email-jetable.fr
  - email-temporaire.cz.cc
  - emlhub.com
  - emlpro.com
  - emltmp.com
  - eoopy.com
  - eu.dnsabr.com
  - eu.dns-cloud.net
  - everybodyweb.com
  - fakemail.top
  - fexbox.org
  - fexbox.ru
  - fexpost.com
  - finemail.org
  - fineoak.org
  - firemailbox.club
  - firste.ml
  - fliegender.fish
  - fouadps.cf
  - freeallapp.com
  - freeml.net
  - freundin.ru
  - from.onmypc.info
  - fshare.ootech.vn
  - fukaru.com
  - geneseeit.com
  - getnada.com
  - gettempmail.com
  - greencafe24.com
  - gripam.com
  - grugrug.ru
  - gu5t.com
  - halumail.com
  - happy-new-year.top
  - harakirimail.se
  - haribu.net
  - hellomail.tech
  - heroku.42web.io
  - hide.biz.st
  - hidemyass.fun
  - historictheology.com
  - hourly.site
  - hubbu.online
  - iamhere.store
  - ianz.pro
  - icenhl.com
  - igosad.tech
  - incognitomail.org
  - inpwa.com
  - intopwa.com
  - intopwa.net
  - intopwa.org
  - jaga.email
  - jetable.co.cc
  - jetable.cz.cc
  - just4fun.me
  - k377.me
  - kaaaxcreators.tk
  - kaengu.ru
  - kentol.buzz
  - ketoblazepro.com
  - kittenemail.com
  - kittenemail.xyz
  - knol-power.nl
  - kost.party
  - kuontil.buzz
  - lackmail.ru
  - lajoska.pe.hu
  - laste.ml
  - lazyinbox.com
  - logicstreak.com
  - lsh.my.id
  - luxusmail.cf
  - luxusmail.ga
  - luxusmail.gq
  - luxusmail.ml
  - luxusmail.my.id
  - luxusmail.tk
  - maa.567map.xyz
  - mac-24.com
  - magspam.net
  - mail7.io
  - mail.a1.wtf
  - mail.ahem.email
  - mailbox.in.ua
  - mailboxvip.com
  - mailgano.com
  - mailgen.biz
  - mailgen.club
  - mailgen.fun
  - mailgen.info
  - mailgen.io
  - mailgen.pro
  - mailgen.pw
  - mailgen.xyz
  - mailglobe.club
  - mailglobe.org
  - mailg.ml
  - mailgun.org
  - mailhazard.com
  - mailhazard.us
  - mailhz.me
  - mail.igosad.me
  - mail-jetable.co.tv
  - mail-jetable.cz.cc
  - mail.kaaaxcreators.tk
  - mail.lgbtiqa.xyz
  - mail.mrgamin.ml
  - mailpoof.com
  - mailsac.com
  - mails.v2-ray.net
  - mailtemp.net
  - mail-temporaire.com
  - mailtemporaire.com
  - mail-temporaire.cz.cc
  - mailtemporaire.fr
  - mailto.plus
  - markmail.site
  - marmaryta.club
  - marmaryta.com
  - marmaryta.email
  - marmaryta.space
  - matapad.com
  - m.cloudns.cl
  - m.discardmail.org
  - mdz.email
  - meadowutilities.com
  - meantinc.com
  - media.motornation.buzz
  - mentonit.net
  - mepost.pw
  - mexcool.com
  - mfsa.ru
  - mhzayt.online
  - mm.8.dnsabr.com
  - moakt.cc
  - moakt.co
  - moakt.ws
  - mobj.site
  - mowgli.jungleheart.com
  - mrdeeps.ml
  - mrgamin.cf
  - mrgamin.gq
  - mrgamin.ml
  - msft.cloudns.asia
  - muell.icu
  - muell.monster
  - muell.ru
  - muell.xyz
  - muellmail.com
  - muellemail.com
  - myinternet.site
  - mymail.infos.st
  - mysukam.com
  - mywrld.top
  - nanozone.net
  - nccedu.media
  - nccedu.team
  - ndeooo.club
  - ndeooo.com
  - ndeooo.xyz
  - netmail.tk
  - nicoric.com
  - noclickemail.com
  - nospamme.rs
  - notmyemail.tech
  - noway.pw
  - now.mefound.com
  - nvc-e.com
  - oida.icu
  - omailer.xyz
  - ondemandemail.top
  - oneideas.xyz
  - onlinemaster.xyz
  - opencube.xyz
  - ottappmail.com
  - outlook-mails.site
  - padpub.co.cc
  - padpub.co.tv
  - panarabanesthesia2021.live
  - papierkorb.me
  - pecinan.com
  - pecinan.net
  - pecinan.org
  - pflege-schoene-haut.de
  - plexvenet.com
  - polostar.me
  - postheo.de
  - powerencry.com
  - ppc-e.com
  - privacy-mail.top
  - pw.8.dnsabr.com
  - pw.epac.to
  - qrtise.com
  - quickbuy4u.online
  - randomail.net
  - rcedu.team
  - revampall.com
  - robot-mail.com
  - rover.info
  - rsvpee.com
  - safeemail.xyz
  - savageattitude.com
  - sexy.camdvr.org
  - shit.dnsabr.com
  - shit.dns-cloud.net
  - sinkafbet.net
  - skug.net
  - slowimo.com
  - smack.email
  - sociallifes.club
  - sokuyo.xyz
  - solpatu.space
  - spambog.com
  - spambog.de
  - spam.care
  - spam.destroyer.email
  - spamsandwich.com
  - speedmail.ze.cx
  - squizzy.net
  - sroff.com
  - ssl.tls.cloudns.asia
  - stepoly.com
  - stevenledford.com
  - supere.ml
  - sweetxxx.de
  - t20mail.com
  - tamchiasao.com
  - tech-guru.site
  - techwizardent.me
  - tempemail.info
  - tempes.gq
  - tempmail.digital
  - tempmail.wizardmail.tech
  - temporary-mail.net
  - tempr.email
  - tempsky.com
  - tempsky.top
  - tempxmail.info
  - the23app.com
  - thejoker5.com
  - throwam.com
  - tls.cloudns.asia
  - tmails.net
  - tmail.ws
  - tmpbox.net
  - tmpmail.net
  - tmpmail.org
  - tmpnator.live
  - tokyoto.site
  - tonne.to
  - tovinit.com
  - trap-mail.de
  - trashmail.es
  - trashmail.win
  - trashmail.ws
  - traz.cafe
  - trbvm.com
  - truthfinderlogin.com
  - ttlrlie.com
  - tuneme.online
  - twitter-sign-in.cf
  - t.woeishyang.com
  - typery.com
  - ultra.fyi
  - vintomaper.com
  - vipmailonly.info
  - viralchoose.com
  - virtualdepot.store
  - virtual-generations.com
  - viruschecks.co
  - vvaa1.com
  - wc.pisskegel.de
  - wearsn.com
  - wellsfargocomcardholders.com
  - wimsg.com
  - wmail.club
  - wmcasinoauto.com
  - xxxxx.cyou
  - yahoo-emails.online
  - yaud.net
  - yeezus.ru
  - yepmail.app
  - yepmail.cc
  - yepmail.club
  - yepmail.co
  - yepmail.id
  - yepmail.in
  - yepmail.to
  - yepmail.us
  - yepmail.ws
  - yomail.info
  - you.has.dating
  - yx.dns-cloud.net
  - zadder.xyz
  - zebins.com
  - zebins.eu
  - zeroe.ml
  - zwoho.com
  - 0815.ru
  - 0wnd.net
  - 0wnd.org
  - 10minmail.de
  - 10minutemail.co.za
  - 10minutemail.com
  - 10minutenmail.xyz
  - 123-m.com
  - 1fsdfdsfsdf.tk
  - 1pad.de
  - 20minutemail.com
  - 21cn.com
  - 2fdgdfgdfgdf.tk
  - 2prong.com
  - 30minutemail.com
  - 33mail.com
  - 3trtretgfrfe.tk
  - 4gfdsgfdgfd.tk
  - 4warding.com
  - 5ghgfhfghfgh.tk
  - 6hjgjhgkilkj.tk
  - 6paq.com
  - 7tags.com
  - 9ox.net
  - a-bc.net
  - agedmail.com
  - ama-trade.de
  - amilegit.com
  - amiri.net
  - amiriindustries.com
  - anonmails.de
  - anonymbox.com
  - antichef.com
  - antichef.net
  - antireg.ru
  - antispam.de
  - antispammail.de
  - armyspy.com
  - artman-conception.com
  - azmeil.tk
  - baxomale.ht.cx
  - beefmilk.com
  - bigstring.com
  - binkmail.com
  - bio-muesli.net
  - bobmail.info
  - bodhi.lawlita.com
  - bofthew.com
  - bootybay.de
  - boun.cr
  - bouncr.com
  - breakthru.com
  - brefmail.com
  - bsnow.net
  - bspamfree.org
  - bugmenot.com
  - bund.us
  - burstmail.info
  - buymoreplays.com
  - byom.de
  - c2.hu
  - card.zp.ua
  - casualdx.com
  - cek.pm
  - centermail.com
  - centermail.net
  - chammy.info
  - childsavetrust.org
  - chogmail.com
  - choicemail1.com
  - clixser.com
  - cmail.net
  - cmail.org
  - coldemail.info
  - cool.fr.nf
  - courriel.fr.nf
  - courrieltemporaire.com
  - crapmail.org
  - cust.in
  - cuvox.de
  - d3p.dk
  - dacoolest.com
  - dandikmail.com
  - dayrep.com
  - dcemail.com
  - deadaddress.com
  - deadspam.com
  - delikkt.de
  - despam.it
  - despammed.com
  - devnullmail.com
  - dfgh.net
  - digitalsanctuary.com
  - dingbone.com
  - disposableaddress.com
  - disposableemailaddresses.com
  - disposableinbox.com
  - dispose.it
  - dispostable.com
  - dodgeit.com
  - dodgit.com
  - donemail.ru
  - dontreg.com
  - dontsendmespam.de
  - drdrb.net
  - dump-email.info
  - dumpandjunk.com
  - dumpyemail.com
  - e-mail.com
  - e-mail.org
  - e4ward.com
  - easytrashmail.com
  - einmalmail.de
  - einrot.com
  - eintagsmail.de
  - emailgo.de
  - emailias.com
  - emaillime.com
  - emailsensei.com
  - emailtemporanea.com
  - emailtemporanea.net
  - emailtemporar.ro
  - emailtemporario.com.br
  - emailthe.net
  - emailtmp.com
  - emailwarden.com
  - emailx.at.hm
  - emailxfer.com
  - emeil.in
  - emeil.ir
  - emz.net
  - ero-tube.org
  - evopo.com
  - existiert.net
  - explodemail.com
  - express.net.ua
  - eyepaste.com
  - fakeinbox.com
  - fakeinformation.com
  - fansworldwide.de
  - fantasymail.de
  - fightallspam.com
  - filzmail.com
  - fivemail.de
  - fleckens.hu
  - frapmail.com
  - friendlymail.co.uk
  - fuckingduh.com
  - fudgerub.com
  - fyii.de
  - garliclife.com
  - gehensiemirnichtaufdensack.de
  - get2mail.fr
  - getairmail.com
  - getmails.eu
  - getonemail.com
  - giantmail.de
  - girlsundertheinfluence.com
  - gishpuppy.com
  - gmial.com
  - goemailgo.com
  - gotmail.net
  - gotmail.org
  - gotti.otherinbox.com
  - great-host.in
  - greensloth.com
  - grr.la
  - gsrv.co.uk
  - guerillamail.biz
  - guerillamail.com
  - gustr.com
  - harakirimail.com
  - hat-geld.de
  - hatespam.org
  - herp.in
  - hidemail.de
  - hidzz.com
  - hmamail.com
  - hopemail.biz
  - ieh-mail.de
  - ikbenspamvrij.nl
  - imails.info
  - inbax.tk
  - inbox.si
  - inboxalias.com
  - inboxclean.com
  - inboxclean.org
  - infocom.zp.ua
  - instant-mail.de
  - ip6.li
  - irish2me.com
  - iwi.net
  - jetable.com
  - jetable.fr.nf
  - jetable.net
  - jetable.org
  - jnxjn.com
  - jourrapide.com
  - jsrsolutions.com
  - kasmail.com
  - kaspop.com
  - killmail.com
  - killmail.net
  - klassmaster.com
  - klzlk.com
  - koszmail.pl
  - kurzepost.de
  - lawlita.com
  - letthemeatspam.com
  - lhsdv.com
  - lifebyfood.com
  - link2mail.net
  - litedrop.com
  - lol.ovpn.to
  - lolfreak.net
  - lookugly.com
  - lortemail.dk
  - lr78.com
  - lroid.com
  - lukop.dk
  - m21.cc
  - mail-filter.com
  - mail-temporaire.fr
  - a.fm.cloudns.nz
  - you-spam.com
  - trash-mail.com
  - vevs.de
  - phaantm.de
  - jrvps.com
  - siaemic.com
  - vpsrec.com
  - re-gister.com
  - nezid.com
  - xcoxc.com
  - jeoce.com
  - cdfaq.com
  - xvlinjury.com
  - ulm-dsl.de
  - opentrash.com
  - knickerbockerban.de
  - muell.io
  - wegwerfemail.de
  - dsgvo.party
  - lambsauce.de
  - ramenmail.de
  - ji5.de
  - ji6.de
  - ji7.de
  - sudern.de
