app:
  host: "http://localhost:3000"
database:
  primary:
    host: localhost
    port: 5432
    username: postgres
    password: postgres
  cache:
    host: localhost
    port: 5432
    username: postgres
    password: postgres
  cable:
    host: localhost
    port: 5432
    username: postgres
    password: postgres
