app:
  host: "http://localhost:3000"
database:
  primary:
    host: localhost
    port: 5432
    username: postgres
    password: postgres
  cache:
    host: localhost
    port: 5432
    username: postgres
    password: postgres
redis:
  url: redis://localhost:6379/1
